name: build_test

# Work in progress. takes forever

on:
  push:

jobs:         
  compilation-test:
    runs-on: 32-core-linux-runner
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          ./docker-build.sh Dockerfile-Ubuntu-20.04
          ./docker-run.sh imx-5.15.71-2.2.2/yocto-build.sh
          
          
